---
- name: helper_generate_secret | regenerate secret key
  command: openssl rand -base64 40
  register: secret_key

- replace:
    path: "{{ project_path }}/{{ project_name }}/local_settings.py"
    regexp: "SECRET_KEY = '###'"
    replace: "SECRET_KEY = '{{ secret_key.stdout }}'"