---
- hosts: geonode
  tasks:
    - import_tasks: ./tasks/os_packages.yml
    - import_tasks: ./tasks/geonode.yml
    - import_tasks: ./tasks/paver_setup.yml
    - import_tasks: ./tasks/postgres.yml
    - import_tasks: ./tasks/apache.yml
    - import_tasks: ./tasks/paver_sync.yml
    - import_tasks: ./tasks/geoserver.yml
    - import_tasks: ./tasks/update_ip.yml
    - import_tasks: ./tasks/generate_secret.yml