---
- name: apache | Write geonode.conf 
  template: src=./templates/apache/geonode.conf.j2 dest=/etc/apache2/sites-available/geonode.conf
  become: yes

- name: apache | Write wsgi.py
  template: src=./templates/apache/wsgi.py.j2 dest={{ project_path }}/{{ project_name }}/wsgi.py
  become: yes

- name: apache | Write local_settings.py
  template: src=./templates/django/local_settings.py.j2 dest={{ project_path }}/{{ project_name }}/local_settings.py
  become: yes

# todo regenerate secret key

#- name: regenerate secret key
#  command: python -c 'import random; print "".join([random.choice("abcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*(-_=+)") for i in range(50)])'
#  register: secret_key

#- replace:
#    path: {{ project_path }}/{{ project_name }}/local_settings.py
#    regexp: "SECRET_KEY = '###'"
#    replace: "SECRET_KEY = '{{ secret_key.stdout }}'"


- name: apache | Activate mod proxy_http
  become: yes
  command: a2enmod proxy_http

- name: apache | Deactivate 000-default virtualhost
  become: yes
  command: a2dissite 000-default

- name: apache | Activate geonode virtualhost
  become: yes
  command: a2ensite geonode

- name: apache | Check config
  command: apache2ctl configtest
  ignore_errors: True

- name: Tomcat | restart
  become: yes
  service:
    name: apache2
    state: restarted


# migrate and collect files
- name: Django | manage.py migrate
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_dir }}"

- name: Django | manage.py collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_dir }}"

# set file permissions
- name: apache | thumbs permissions
  file:
    path: "{{ project_path }}/{{ project_name }}/uploaded/thumbs"
    state: directory
    mode: 0777

- name: apache | layers permissions
  file:
    path: "{{ project_path }}/{{ project_name }}/uploaded/layers"
    state: directory
    mode: 0777

- name: apache | project path permissions
  become: yes
  file:
    path: "{{ project_path }}"
    owner: "{{ user }}"
    recurse: yes

- name: apache | static permissions
  become: yes
  file:
    path: "{{ project_path }}/{{ project_name }}/static"
    owner: "{{ user }}"
    group: www-data
    recurse: yes

- name: apache | uploaded permissions
  become: yes
  file:
    path: "{{ project_path }}/{{ project_name }}/uploaded"
    owner: "{{ user }}"
    group: www-data
    recurse: yes

- name: apache | static_root permissions
  become: yes
  file:
    path: "{{ project_path }}/{{ project_name }}/static_root"
    recurse: yes
    mode: 0777