---
- name: apache2 | Write geonode.conf 
  template: src=./templates/apache/geonode.conf.j2 dest=/etc/apache2/sites-available/geonode.conf
  become: yes

- name: apache2 | Write wsgi.py
  template: src=./templates/apache/wsgi.py.j2 dest={{project_path}}/{{project_name}}/wsgi.py
  become: yes

- name: apache2 | Write local_settings.py
  template: src=./templates/django/local_settings.py.j2 dest={{project_path}}/{{project_name}}/local_settings.py
  become: yes

- name: apache2 | Activate mod proxy_http
  become: yes
  command: a2enmod proxy_http

- name: apache2 | Deactivate 000-default virtualhost
  become: yes
  command: a2dissite 000-default

- name: apache2 | Activate geonode virtualhost
  become: yes
  command: a2ensite geonode

- name: apache2 | Check config
  command: apache2ctl configtest
  ignore_errors: True

- name: Tomcat | start
  become: yes
  service:
    name: apache2
    state: start


# migrate and collect files
- name: Django | manage.py migrate
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_dir }}"

- name: Django | manage.py collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_dir }}"

# set file permissions
- name: apache2 | thumbs permissions
  file:
    path: "{{project_path}}/{{project_name}}/uploaded/thumbs"
    state: directory
    mode: 0777

- name: apache2 | layers permissions
  file:
    path: "{{project_path}}/{{project_name}}/uploaded/layers"
    state: directory
    mode: 0777

- name: apache2 | project path permissions
  file:
    path: "{{project_path}}"
    owner: geonode
    recurse: yes

- name: apache2 | static permissions
  file:
    path: "{{project_path}}/{{project_name}}/static"
    owner: geonode
    group: www-data
    recurse: yes

- name: apache2 | uploaded permissions
  file:
    path: "{{project_path}}/{{project_name}}/uploaded"
    owner: geonode
    group: www-data
    recurse: yes

- name: apache2 | static_root permissions
  file:
    path: "{{project_path}}/{{project_name}}/static_root"
    recurse: yes
    mode: 0777