---
- name: geoserver | Tomcat stop
  become: yes
  service:
    name: tomcat8
    state: stopped

- pause:
    minutes: 1

- name: geoserver | Copy Geoserver directory
  become: yes
  command: cp -Rf {{ project_path }}/geoserver/geoserver/ /var/lib/tomcat8/webapps/

- name: geoserver | Set permissions /var/lib/tomcat8/webapps/geoserver'
  become: yes
  command: 'chown -Rf tomcat8: /var/lib/tomcat8/webapps/geoserver'


- name: geoserver | Create /data/geoserver-data
  become: yes
  command: mkdir -p /data/geoserver-data

- name: geoserver | Create /data/geoserver-logs
  become: yes
  command: mkdir -p /data/geoserver-logs

- name: geoserver | Create /data/gwc_cache_dir
  become: yes
  command: mkdir -p /data/gwc_cache_dir


- name: geoserver | Copy Geoserver Data directory
  become: yes
  command: cp -Rf {{ project_path }}/geoserver/data/. /data/geoserver-data/


- name: geoserver | Set permissions /data/geoserver-data/
  become: yes
  command: 'chown -Rf tomcat8: /data/geoserver-data/'

- name: geoserver | Set permissions /data/geoserver-logs/
  become: yes
  command: 'chown -Rf tomcat8: /data/geoserver-logs/'

- name: geoserver | Set permissions /data/gwc_cache_dir/
  become: yes
  command: 'chown -Rf tomcat8: /data/gwc_cache_dir/'

- name: geoserver | Write tomcat-users.xml
  template: src=./templates/gs/tomcat-users.xml dest=/etc/tomcat8/tomcat-users.xml
  become: yes

- name: apache | Permissions tomcat-users.xml
  become: yes
  file:
    path: /etc/tomcat8/tomcat-users.xml
    owner: root
    group: tomcat8


- name: geoserver | Write tomcat8
  template: src=./templates/gs/tomcat8 dest=/etc/default/tomcat8
  become: yes

- name: geoserver | Write catalina.properties
  template: src=./templates/gs/catalina.properties dest=/var/lib/tomcat8/conf/catalina.properties
  become: yes

- name: geoserver | Write config.conf 
  template: src=./templates/gs/config.xml.j2 dest=/data/geoserver-data/security/filter/geonode-oauth2/config.xml
  become: yes

- name: apache | Permissions config.conf 
  become: yes
  file:
    path: /data/geoserver-data/security/filter/geonode-oauth2/config.xml
    owner: tomcat8
    group: tomcat8

- name: geoserver | Write global.xml 
  template: src=./templates/gs/global.xml.j2 dest=/data/geoserver-data/global.xml
  become: yes

- name: apache | Permissions /data/geoserver-data/global.xml
  become: yes
  file:
    path: /data/geoserver-data/global.xml
    owner: tomcat8
    group: tomcat8

- name: geoserver | Tomcat start
  become: yes
  service:
    name: tomcat8
    state: started