---
- name: install_geonode_packages | install list of dependency packages
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - python-virtualenv
      - python-dev
      - libxml2
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - libjpeg-dev
      - libpq-dev
      - git
      - default-jdk
      - build-essential
      # - openssh-server
      - gettext
      - nano
      - vim 
      - unzip 
      - zip 
      - patch 
      - git-core 
      - postfix
      - software-properties-common

- name: install_geonode_packages | add oracle java repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java'

- name: install_geonode_packages | accept java8 license
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

- name: install_geonode_packages | install oracle java 8
  become: yes
  apt: name={{item}} state=latest
  loop: ['oracle-java8-installer', 'ca-certificates', 'oracle-java8-set-default']

- name: install_geonode_packages | add ubuntugis repository
  become: yes
  apt_repository: repo='ppa:ubuntugis'

- name: install_geonode_packages | upgrade apt packages
  become: true
  apt:
    upgrade: yes

- name: install_geonode_packages | add ubuntugis/ppa repository
  become: yes
  apt_repository: repo='ppa:ubuntugis/ppa'

- name: install_geonode_packages | upgrade apt packages
  become: true
  apt:
    upgrade: yes

- name: install_geonode_packages | install a list of dependency packages
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - gcc
      - apache2
      - libapache2-mod-wsgi
      - libgeos-dev
      - libjpeg-dev
      - libpng-dev
      - libpq-dev 
      - libproj-dev 
      - libxml2-dev 
      - libxslt-dev

- name: install_geonode_packages | add ubuntugis/ubuntugis-testing repository
  become: yes
  apt_repository: repo='ppa:ubuntugis/ubuntugis-testing'

- name: install_geonode_packages | install a list of dependency packages
  become: yes
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - gdal-bin 
      - libgdal20 
      - libgdal-dev
      - python-gdal 
      - python-pycurl 
      - python-imaging 
      - python-pastescript 
      - python-psycopg2 
      - python-urlgrabber
      - postgresql 
      - postgis 
      - postgresql-9.5-postgis-scripts 
      - postgresql-contrib
      - tomcat8
      # remove after testing
      - tomcat8-admin

- name: install_geonode_packages | upgrade apt packages
  become: yes
  apt:
    upgrade: yes
    autoremove: yes
    autoclean: yes
    purge: yes