---
install_root: /home/vagrant
project_name: my_geonode
django_version: 1.11.15

# server ip or domain without http[s]
server_name: 192.168.33.11

virtualenv_dir: "{{install_root}}/.venv/{{project_name}}"
project_path: "{{install_root}}/{{project_name}}"

db_user: geonode
db_password: geonode